增加功能-按不同环境切换配置文件
RayWangQvQ/BiliBiliTool pull request #212
Opened 2020-11-30 09:49 UTC by hjkl950217

2020-12-01 11:41 UTC, hjkl950217 commented
有点小bug 以后再来提

2020-12-01 14:52 UTC, hjkl950217 commented
#262

2020-12-02 08:33 UTC, RayWangQvQ requested changes

2020-12-02 08:33 UTC, RayWangQvQ commented on .github/workflows/bilibili-daily-task.yml
> +  #push: # push触发
有人提交PR直接删掉了，这儿冲突的话建议删掉

2020-12-02 08:33 UTC, RayWangQvQ commented on .github/workflows/bilibili-daily-task.yml
> +        ASPNETCORE_ENVIRONMENT: ${{secrets.ENV}} # 方便切换不同的appsettings文件 也可以在不同的action yml文件中配置来同时运行多个任务
这儿不建议开放`ENV`为Secrets配置，理论上发布的项目`ENV`就应该是`PRD`，不应该是别的什么值。
用它来切换使用哪个配置文件也有点怪，线上跑action还是推荐全部使用secrets配置，想要多账号的话，可以多加一份secrets和一个yml文件。

2020-12-02 08:33 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Application/Attributes/TaskInterceptorAttribute.cs
> +            _logger = RayContainer.GetLogger<TaskInterceptorAttribute>();
哈哈哈机智，用Service Locator解决了，棒

2020-12-02 08:38 UTC, hjkl950217 commented on src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs
> +            this._logger = logger;
自动保存加的this。这个文件中我只有一个地方是修改的

2020-12-02 08:38 UTC, hjkl950217 commented on src/Ray.BiliBiliTool.DomainService/ChargeDomainService.cs
> +                this._logger.LogInformation("B币券余额小于2,无法充电");
主要是为了修改这里。我发'<'后面的在微信上面似乎被过滤了

2020-12-02 08:38 UTC, hjkl950217 commented on src/Ray.BiliBiliTool.Config/Extensions/IDictionaryExtensions.cs
> +    public static class IDictionaryExtensions
扩展方法是这样的：
如果对`IDictionary`扩展，文件名为`IDictionaryExtensions.cs`，命名空间是`IDictionary`所在的命名空间 。  这个是参考其它库和官方库的做法。

2020-12-02 08:38 UTC, hjkl950217 commented on .github/workflows/bilibili-daily-task.yml
> +  #push: # push触发
应该自动合并了，有冲突的话我会解决哒

2020-12-02 08:41 UTC, RayWangQvQ commented
感谢贡献代码，很棒的内容！
但朋友你这一次性也提交了太多东西了...有些新功能内容和优化内容放在一起了，我review起来有点困难。
比如，有些文件专门为私有变量加了`this.`，这种其实单独提一个优化类PR一起讨论下，因为有些IDE或插件其实是会反过来去掉`this.`，比如resharper。

2020-12-02 08:41 UTC, hjkl950217 commented on .github/workflows/bilibili-daily-task.yml
> +        ASPNETCORE_ENVIRONMENT: ${{secrets.ENV}} # 方便切换不同的appsettings文件 也可以在不同的action yml文件中配置来同时运行多个任务
用`ASPNETCORE_ENVIRONMENT`是和默认情况下的程序行为一致。

默认情况下不配置的话，不是PRD模式的，而是开发者模式。
 想要开放的目的是：我fork主库之后，自己会修改`appsetting.json`，但是这样在下次同步主库代码时就会冲突，所以我增加一个配置文件利用不同环境加载配置文件的方法来达到兼容效果。

另一个是：PR里不是有不少人修改了appsetting.json然后来提PR的嘛(谁让github的同步操作需要反着来)。  有这个功能后也能减少类似的冲突

2020-12-02 08:42 UTC, hjkl950217 commented on src/Ray.BiliBiliTool.Application/Attributes/TaskInterceptorAttribute.cs
> +            _logger = RayContainer.GetLogger<TaskInterceptorAttribute>();
但也不是很好。  我看启动时你创建一个作用域才能这样玩。如果是web项目，这样就有潜在的问题了，不在一个作用域阿

2020-12-02 08:48 UTC, hjkl950217 commented
@RayWangQvQ  this这个是修改<符号 保存后导致的，哈哈。
本来想提多次，但是现在随时要调整(主库因某个原因要改代码，我懂)。 我这边跟着调整，然后又没有即时合PR导致的。
this这个其实我和人讨论过多次，结果是对代码含义无所谓。但我个人还是想要明确this和base,理由如下:

1. 能一眼知道是当前类所拥有的东西(父类的也能this，但能表示是类拥有的)
2. 我知道许多人用'_'来替代"this"的作用(resharp的默认行为)。 但VS默认规则又是不加。  我个人是习惯不加的。
3. 排除前缀问题， 假如一个方法体中包含：局部变量、本地函数、委托变量、using static引入的东西...  这时this能让你清楚的分辨“本类代码”和“外部代码”

2020-12-02 08:48 UTC, hjkl950217 commented
冲突的问题我等我解决一下

2020-12-02 08:55 UTC, hjkl950217 commented
yml的自动触发建议留着吧(以注释的方式)。。万一以后有什么用或是想要这2行脚本，就不用找拉

2020-12-02 09:04 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.DomainService/ChargeDomainService.cs
> +                this._logger.LogInformation("B币券余额小于2,无法充电");
了解

2020-12-02 09:15 UTC, RayWangQvQ commented on src/Ray.BiliBiliTool.Config/Extensions/IDictionaryExtensions.cs
> +    public static class IDictionaryExtensions
我印象中官方库应该没有这种做法吧，顺手去.net文档翻了下：
https://docs.microsoft.com/zh-cn/dotnet/api/system.collections.generic.collectionextensions?view=net-5.0

2020-12-02 09:16 UTC, RayWangQvQ commented on .github/workflows/bilibili-daily-task.yml
> +        ASPNETCORE_ENVIRONMENT: ${{secrets.ENV}} # 方便切换不同的appsettings文件 也可以在不同的action yml文件中配置来同时运行多个任务
被你说服了

2020-12-02 09:17 UTC, hjkl950217 commented on src/Ray.BiliBiliTool.Config/Extensions/IDictionaryExtensions.cs
> +    public static class IDictionaryExtensions
有的，这个是从.net core时代开始的。 web项目中注册服务的方法都是挂在对应的命名空间下面。
但是文件名的话却各有不同。
我=哈翻一下贴出来。

2020-12-02 09:20 UTC, hjkl950217 commented on .github/workflows/bilibili-daily-task.yml
> +        ASPNETCORE_ENVIRONMENT: ${{secrets.ENV}} # 方便切换不同的appsettings文件 也可以在不同的action yml文件中配置来同时运行多个任务
哈哈 估计你被PR弄烦了。。我是自己合代码时觉得烦的。。。

2020-12-02 09:22 UTC, RayWangQvQ commented
> @RayWangQvQ this这个是修改<符号 保存后导致的，哈哈。
> 本来想提多次，但是现在随时要调整(主库因某个原因要改代码，我懂)。 我这边跟着调整，然后又没有即时合PR导致的。
> this这个其实我和人讨论过多次，结果是对代码含义无所谓。但我个人还是想要明确this和base,理由如下:
> 
> 1. 能一眼知道是当前类所拥有的东西(父类的也能this，但能表示是类拥有的)
> 2. 我知道许多人用'_'来替代"this"的作用(resharp的默认行为)。 但VS默认规则又是不加。  我个人是习惯不加的。
> 3. 排除前缀问题， 假如一个方法体中包含：局部变量、本地函数、委托变量、using static引入的东西...  这时this能让你清楚的分辨“本类代码”和“外部代码”

`this.log`没问题，但是`this._log`看着还是有点多余的。
但是这个只是规范或习惯问题，对功能没有影响，那先不管了，等有机会以后再做个统一吧。

2020-12-02 09:25 UTC, hjkl950217 commented
嗯。。不过这是开源库要面临的一个问题：不同贡献者的格式设置不同

2020-12-02 09:28 UTC, RayWangQvQ commented
> yml的自动触发建议留着吧(以注释的方式)。。万一以后有什么用或是想要这2行脚本，就不用找拉

有人发PR要删，我自己想了下，好像确实也没有push后非要跑一下的需求，而且本身又是每日任务类的应用，估计以后应该也没有这样的需求了，删了就删了吧。

2020-12-02 09:33 UTC, hjkl950217 commented
也行。。  回复引用怎么玩的？ 我还不会。。我只会 # @hjkl950217

2020-12-02 09:36 UTC, RayWangQvQ commented
右上角可以引用：
![image](https://user-images.githubusercontent.com/31154238/100855142-d4998f80-34c4-11eb-93bf-b5aa3c931bb2.png)

2020-12-02 09:36 UTC, hjkl950217 commented
> 右上角可以引用：
> ![image](https://user-images.githubusercontent.com/31154238/100855142-d4998f80-34c4-11eb-93bf-b5aa3c931bb2.png)

Get

2020-12-02 09:40 UTC, merged

2020-12-02 09:44 UTC, RayWangQvQ commented
已合并，感谢提供PR，之前star和fork一直增长，就是没人愿意来贡献PR，现在终于有人愿意来PR优化我的辣鸡代码了。

2020-12-02 09:47 UTC, hjkl950217 commented
没有没有。。我也是.neter 难得看到一个用C#写的这种“实用小工具”，能贡献一点微博之力蛮好的。

你的代码可不垃圾，良好的代码规范，使用了类似ABP的结构，非常好的！ 我刚才还和隔壁同事吹这个项目